"""Standalone text-description evaluator plugin for fashion prompts."""

from .design_text_evaluator_api import (
    DEFAULT_HF_LOCAL_GRPO_MODEL,
    DesignTextEvaluator,
    default_hf_grpo_epochs_per_round,
    default_hf_grpo_rounds,
    default_hf_local_grpo_model,
    default_hf_local_grpo_ref_model,
    default_odin_rm_model,
    grpo_config,
    grpo_design_text_evaluator_config,
    grpo_hf_local_training_config,
    grpo_odin_rm_config,
    grpo_parallel_k_rewrite_config,
    grpo_rewriter_llm_config,
    grpo_training_data_config,
    load_default_evaluator,
)
from .r_content_reward import (
    apply_group_z_len_r_content,
    apply_length_disentangle,
    build_r_content_payload,
    fit_holdout_length_centered,
    fit_holdout_length_regression,
    pearson_corr,
    summarize_length_leakage,
)
from .score_formula import (
    LENGTH_DISENTANGLE_MODES,
    R_CONTENT_PENALTY_MERGE,
    build_score_formula_breakdown,
    build_mode_explanations,
    explain_length_mode,
    explain_penalty_merge,
    interpret_length_disentangle,
    refresh_score_formula_r_content,
)

__all__ = [
    "DEFAULT_HF_LOCAL_GRPO_MODEL",
    "DesignTextEvaluator",
    "load_default_evaluator",
    "default_hf_local_grpo_model",
    "default_hf_local_grpo_ref_model",
    "default_hf_grpo_rounds",
    "default_hf_grpo_epochs_per_round",
    "default_odin_rm_model",
    "grpo_config",
    "grpo_design_text_evaluator_config",
    "grpo_hf_local_training_config",
    "grpo_odin_rm_config",
    "grpo_parallel_k_rewrite_config",
    "grpo_rewriter_llm_config",
    "grpo_training_data_config",
    "apply_group_z_len_r_content",
    "apply_length_disentangle",
    "build_r_content_payload",
    "build_score_formula_breakdown",
    "build_mode_explanations",
    "explain_length_mode",
    "explain_penalty_merge",
    "fit_holdout_length_centered",
    "fit_holdout_length_regression",
    "pearson_corr",
    "summarize_length_leakage",
    "interpret_length_disentangle",
    "LENGTH_DISENTANGLE_MODES",
    "R_CONTENT_PENALTY_MERGE",
    "refresh_score_formula_r_content",
]
